spring.application.name=rate-limiter-service
server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6379

ratelimiter.default.limit=10
ratelimiter.default.window-seconds=60
ratelimiter.default.algorithm=sliding_window

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=always