spring.application.name=rate-limiter-service
server.port=${PORT:8080}

spring.data.redis.host=localhost
spring.data.redis.port=6379

ratelimiter.default.limit=10
ratelimiter.default.window-seconds=60
ratelimiter.default.algorithm=sliding_window

management.endpoints.web.exposure.include=health,info

management.endpoint.health.show-details=always
management.endpoints.web.cors.allowed-origins=https://nikdlabs.github.io,http://localhost:5500,http://127.0.0.1:5500
management.endpoints.web.cors.allowed-methods=GET